# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AhgzIWXopjsyP3XcRBhGMHg9tkmC9eba
"""

# 従業員情報の設定
emp_info = {}
emp_info["古里"] = "00001"
emp_info["有賀"] = "00002"
emp_info["柴崎"] = "00003"

# パスワード認証モード（1:オン 0:オフ）
mode = 1

# 閾値の設定
threshold = 0.5